### ISSUE TITLE
Follow committee v2

### ISSUE THREAD

**Issue by qsona** [willnet/committee-rails#1]
Committee v2-pre versions are being released.
Currently, error occurs if we use committee v2 and committee-rails v0.1.0.

It fails at this point
https://github.com/interagent/committee/blob/master/lib/committee/router.rb#L19
Now the class of `@schema` is `JsonSchema::Schema`, and it doesn't have `routes` method.

Could you please make some implementation to be compatible with newer committee?
Thanks.

**Comment by willnet** [comment]
Fixed by #2.Thanks!
